platform :ios, '8.0'
use_frameworks!

workspace 'Actor'
project 'Actor.xcodeproj'

inhibit_all_warnings!

target 'Actor' do
    project 'Actor.xcodeproj'
    pod 'ActorSDK-iOS'
    pod 'Fabric'
    pod 'Crashlytics'
end
